version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
      - mysql
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - MONGO_URI=mongodb://mongodb:27017/
      - MYSQL_HOST=mysql
      - REDIS_URL=redis://redis:6379

  celery:
    build: .
    command: celery -A task_management worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=resume_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=resume_logs
      - MYSQL_USER=resume_user
      - MYSQL_PASSWORD=resume_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
  mysql_data: 